# Site specific settings
title: "Albert Aparicio"
name: "Albert Aparicio Personal Site"
keywords: "albert, aparicio, personal, site"
baseurl: ""
url: "https://albertaparicio.github.io/"
description: "Website description"
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
#lang_alternate: "pt_BR"
ssl: false # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
#disqus: test
#twitter: 
#facebook: 
#github: 
#google:

# Build settings
markdown: kramdown
permalink: /:categories/:title/
